collision_object_manager:
  ros__parameters:
    namespace:   ""
    synchronous: true
    object_properties_urls:
      - package://aist_fastening_tools/config/fastening_tools_properties.yaml
      - package://aist_description/parts/config/parts_properties.yaml
    touch_links_urls:
      - package://aist_routines/config/touch_links.yaml
