$(var driver_ns):
  ros__parameters:
    usb_port:               $(var usb_port)
    dxl_baud_rate:          $(var baud_rate)
    dxl_read_period:        0.010
    dxl_write_period:       0.010
    use_joint_states_topic: false
    use_moveit:             false
    mobile_robot_config:
      separation_between_wheels: 0.000
      radius_of_wheel:           0.000
    dynamixel_info:         /tmp/$(var driver_ns)_dynamixel_info.yaml
