$(var name)_controller:
  ros__parameters:
    driver_ns:          $(var driver_ns)
    motor_id:           $(var motor_id)
    min_position:       0.000
    max_position:       0.010
    max_effort:         0.5
    min_position_count: 2300
    max_position_count: 2050
    min_effort_count:   7
    max_effort_count:   13
    stall_timeout:      1.0
