screw_tools_fastening_driver:
  ros__parameters:
    usb_port:               /dev/ttyUSB0
    dxl_baud_rate:          1000000
    dxl_read_period:        0.010
    dxl_write_period:       0.010
    use_joint_states_topic: false
    use_moveit:             false
    dynamixel_info:         dynamixel_info.yaml
    mobile_robot_config:
      separation_between_wheels: 0.500
      radius_of_wheel:           0.050

screw_tool_m3_fastening_controller:
  ros__parameters:
    driver_ns:      screw_tools_fastening_driver
    motor_id:       2
    control_period: 0.010
    control_parameters:
      loosen_period:      1.0
      max_stall_speed:    0.01
      min_stall_period:   0.5
      max_noload_current: 0.03
      min_noload_period:  0.5

screw_tool_m4_fastening_controller:
  ros__parameters:
    driver_ns:      screw_tools_fastening_driver
    motor_id:       3
    control_period: 0.010
    control_parameters:
      loosen_period:      1.0
      max_stall_speed:    0.01
      min_stall_period:   0.5
      max_noload_current: 0.03
      min_noload_period:  0.5
