camera_name: g_bot_camera
robot_name: g_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: g_bot_gripper_tip_link
robot_effector_tip_frame: g_bot_gripper_tip_link
camera_parent_frame: g_bot_gripper_base_link
marker_map: aruco-100_101_102_103-105x105-7
enclosed_marker: false
planarity_tolerance: 0.003
initpose: [0.00, -0.40, 0.30, 0, 0, 90]
keyposes:
  - [-0.00, -0.23, 0.05, -30,   0, 90]
  - [-0.00, -0.23, 0.05, -15,   0, 90]
  - [-0.00, -0.23, 0.05,   0,   0, 90]

  - [ 0.00, -0.23, 0.05,  15,   0, 90]
  - [ 0.00, -0.23, 0.05,  30,   0, 90]

  - [ 0.00, -0.26, 0.05, 0, -30.0, 90]
  - [ 0.00, -0.24, 0.05, 0, -15.0, 90]
  - [ 0.00, -0.23, 0.05, 0,   7.5, 90]
  - [ 0.00, -0.21, 0.05, 0,  15.0, 90]
