string                   object_type  # object type
---
string                   object_type  # echo back of the requested object type
aist_msgs/LinkGeometry[] visual_array
aist_msgs/LinkGeometry[] collision_array
aist_msgs/Material[]     material_array   # Not used for COLLADA meshes
