# - Create a new collision object with 'object_id' of 'object_type'.
# - Its location is deteremined as the pose of the object's subframe,
#   'subframe', specified by 'pose' described with respect to 'frame_id'.
#
uint8 CREATE_OBJECT=1

# - Remove a collision object specified by 'object_id'.
# - If 'object_id' is empty, all collision objects attached to 'frame_id'
#   will be removed.
# - If 'frame_id' is also empty, all collision objects in the scene
#   will be removed.
#
uint8 REMOVE_OBJECT=2

# - Make 'base_link' of the existing collision object with 'object_id'
#   a child of 'frame_id'.
# - The object is attached to the closest attachable ascendant link
#   of 'frame_id'.
uint8 ATTACH_OBJECT=3

# - Move the existing collision objectDetach the existing attached collision object with 'object_id'
#   from the link currently attached to.
# - Make 'base_link' of the detached object a child of 'frame_id'
#
uint8 DETACH_OBJECT=4

# - Detach the existing collision object with 'object_id' from the target link
#   currently attached to.
#
uint8 MOVE_OBJECT=5

# - Append touch links associated with the link specified by 'frame_id'
#   to the existing touch links of the object specified by 'object_id'.
#
uint8 APPEND_TOUCH_LINKS=6

# - Remove touch links associated with the link specified by 'frame_id'
#   from the existing touch links of the object specified by 'object_id'.
#
uint8 REMOVE_TOUCH_LINKS=7

# - Set touch_links to the parent link for all attached collision object
#
uint8 RESET_TOUCH_LINKS=8

# - Return infomation of the object specified by 'object_id' in 'info'.
#
uint8 GET_OBJECT_INFO=9

# - Return infomation of the attached object which is a child of the frame
#   specified by 'frame_id' in 'info'.
#
uint8 GET_ATTACHED_CHILD_OBJECT_INFO=10

uint8                         op
string                        object_type
string                        object_id
string                        subframe
string                        frame_id
geometry_msgs/Pose            pose
string                        leaf_id
---
bool                          success
aist_msgs/CollisionObjectInfo info