<?xml version="1.0"?>
<package format="3">
  <name>airec3_moveit_config</name>
  <version>1.19.0</version>
  <description>The airec3_moveit_config package</description>
  <maintainer email="trba-support@robotics.tokyo">Tokyo Robotics Inc.</maintainer>
  <author email="sato@robotics.tokyo">Takashi Sato</author>
  <license>TODO</license>
  <url type="website">https://robotics.tokyo/</url>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_fake_controller_manager</exec_depend>
  <exec_depend>moveit_kinematics</exec_depend>
  <exec_depend>moveit_planners_ompl</exec_depend>
  <exec_depend>moveit_ros_visualization</exec_depend>
  <exec_depend>moveit_setup_assistant</exec_depend>
  <exec_depend>warehouse_ros_mongo</exec_depend>
  <exec_depend>trac_ik</exec_depend>
  <exec_depend>industrial_trajectory_filters</exec_depend>
  <exec_depend>xacro</exec_depend>

  <build_depend>aist_description</build_depend>
  <exec_depend>torobo_description</exec_depend>
  <exec_depend>aist_description</exec_depend>
  <exec_depend condition="$ROS_DISTRO == melodic">mongodb_store</exec_depend>

</package>
