################################
#  robot_description_provider  #
################################
robot_description_provider:
  ros__parameters:
    root_frame: world

####################
#  mesh_generator  #
####################
mesh_generator:
  ros__parameters:
    screen_frame:    virtual_screen
    reference_frame: world
    nsteps_u:        10
    nsteps_v:        10

################
#  nep_bridge  #
################
nep_bridge:
  ros__parameters:
    nep_ip:      10.66.171.39
    wait_time:   7.0
    period:      0.1    # polling period of incoming NEP messages in seconds
    config_file: package://aist_routines/config/inc/nep_bridge_assembly.yaml

#################
#  CLI clients  #
#################
base:
  ros__parameters:
    reference_frame: workspace_center
    moveit_eef_step: 0.002
    collision_object_manager:
      synchronous: true
      period:      0.1
      object_properties_urls:
        - package://aist_description/parts/config/parts_properties.yaml
      touch_links_urls:
        - package://aist_routines/config/inc/touch_links.yaml
