################################
#  robot_description_provider  #
################################
robot_description_provider:
  ros__parameters:
    root_frame: world

####################
#  mesh_generator  #
####################
mesh_generator:
  ros__parameters:
    screen_frame:    virtual_screen
    reference_frame: world
    nsteps_u:        10
    nsteps_v:        10

################
#  nep_bridge  #
################
nep_bridge:
  ros__parameters:
    nep_ip:      192.168.10.106
    wait_time:   7.0
    period:      0.1    # polling period of incoming NEP messages in seconds
    config_file: package://aist_routines/config/inc/nep_bridge_hmi_test.yaml
