base:
  ros__parameters:
    reference_frame: workspace_center
    moveit_eef_step: 0.002
    setting_urls:
      - package://aist_routines/config/inc/base.yaml

kitting:
  ros__parameters:
    reference_frame: workspace_center
    moveit_eef_step: 0.002
    setting_urls:
      - package://aist_routines/config/inc/base.yaml
      - package://aist_routines/config/inc/kitting.yaml

assembly:
  ros__parameters:
    reference_frame: workspace_center
    moveit_eef_step: 0.002
    setting_urls:
      - package://aist_routines/config/inc/base.yaml
      - package://aist_routines/config/inc/assembly.yaml
