precision_gripper_driver:
  ros__parameters:
    usb_port:               /dev/ttyUSB1
    dxl_baud_rate:          57600
    dxl_read_period:        0.010
    dxl_write_period:       0.010
    use_joint_states_topic: false
    use_moveit:             false
    dynamixel_info:         dynamixel_info.yaml
    mobile_robot_config:
      separation_between_wheels: 0.000
      radius_of_wheel:           0.000

precision_gripper_controller:
  ros__parameters:
    driver_ns:      precision_gripper_driver
    motor_id:       1
