picking_parameters:
  base:
    approach_offset:  [0.000, 0.000,  0.060, 0.0, 0.0, 0.0]
    #pick_offset:      [0.000, 0.000, -0.014, 0.0, 0.0, 0.0]
    pick_offset:      [0.000, 0.000,  0.000, 0.0, 0.0, 0.0]
    departure_offset: [0.000, 0.000,  0.060, 0.0, 0.0, 0.0]
    speed_fast:       0.05
    speed_slow:       0.01
    gripper_parameters:
      grasp_position:   0.000
      release_position: 3.140
      max_effort:       30.0
  panel_motor:
    approach_offset:  [0.000, 0.000,  0.120, 0.0, -20.0, 0.0]
    pick_offset:      [0.000, 0.000, -0.020, 0.0, -20.0, 0.0]
    departure_offset: [0.000, 0.000,  0.120, 0.0, -20.0, 0.0]
    speed_fast:       0.1
    speed_slow:       0.1
    gripper_parameters:
      grasp_position:   0.000
      release_position: 0.025
      max_effort:       30.0
  panel_bearing:
    approach_offset:  [0.000, 0.000,  0.120, 0.0, -20.0, 0.0]
    pick_offset:      [0.000, 0.000, -0.020, 0.0, -20.0, 0.0]
    departure_offset: [0.000, 0.000,  0.120, 0.0, -20.0, 0.0]
    speed_fast:       0.1
    speed_slow:       0.1
    gripper_parameters:
      grasp_position:   0.000
      release_position: 0.025
      max_effort:       30.0
  screw_m3:
    approach_offset:  [0.000, 0.000,  0.080, 0.0, 0.0, 0.0]
    pick_offset:      [0.000, 0.000,  0.000, 0.0, 0.0, 0.0]
    departure_offset: [0.000, 0.000,  0.120, 0.0, 0.0, 0.0]
    speed_fast:       0.1
    speed_slow:       0.01
    gripper_parameters:
      suck_min_period:        0.5
      blow_min_period:        0.2
      spiral_npoints:         36
      spiral_angle_increment: 30.0
      spiral_radius_x_max:    0.002
      spiral_radius_y_max:    0.0005
      spiral_speed:           0.001
      spiral_accel:           1.0
      spiral_timeout:         30.0
      seek_speed:             0.2
  screw_m4:
    approach_offset:  [0.000, 0.000,  0.080, 0.0, 0.0, 0.0]
    pick_offset:      [0.000, 0.000,  0.000, 0.0, 0.0, 0.0]
    departure_offset: [0.000, 0.000,  0.120, 0.0, 0.0, 0.0]
    speed_fast:       0.1
    speed_slow:       0.01
    gripper_parameters:
      suck_min_period:        0.5
      blow_min_period:        0.2
      spiral_npoints:         36
      spiral_angle_increment: 30.0
      spiral_radius_x_max:    0.002
      spiral_radius_y_max:    0.0005
      spiral_speed:           0.001
      spiral_accel:           1.0
      spiral_timeout:         30.0
      seek_speed:             0.2
