sweep_parameters:
  04_37D-GEARMOTOR-50-70:
    sweep_length: 0.030
    approach_offset: [0.0, 0.0, 0.15]
    sweep_offset: [0.0, 0.0, 0.001]
    departure_offset: [0.0, 0.0, 0.15]
    speed_fast: 1.0
    speed_slow: 0.1
  05_MBRFA30-2-P6:
    sweep_length: 0.030
    approach_offset: [0.0, -0.015, 0.15]
    sweep_offset: [0.0, -0.015, -0.012]
    departure_offset: [0.0, 0.0, 0.15]
    speed_fast: 1.0
    speed_slow: 0.02
