<?xml version="1.0"?>
<package format="3">

  <name>aist_fastening_tools</name>
  <version>1.1.0</version>
  <description>The aist_fastening_tools package</description>

  <maintainer email="t.ueshiba@aist.go.jp">Toshio UESHIBA</maintainer>
  <license>BSD</license>
  <author email="t.ueshiba@aist.go.jp">Toshio UESHIBA</author>
  <url type="repository">https://github.com/Automation-Research-Team/artros</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>dynamixel_workbench_controllers</exec_depend>
  <exec_depend>aist_bringup</exec_depend>

  <depend>rclcpp_components</depend>
  <depend>rclcpp_action</depend>
  <depend>rclpy</depend>
  <depend>dynamixel_workbench_msgs</depend>
  <depend>ddynamic_reconfigure2</depend>
  <depend>aist_utility</depend>
  <depend>aist_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
