camera_name: b_bot_camera
robot_name: b_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: b_bot_gripper_base_link
robot_effector_tip_frame: b_bot_gripper_tip_link
camera_parent_frame: b_bot_gripper_base_link
marker_map: aruco-100_101_102_103-105x105-7
enclosed_marker: true
detection_mode: 1
planarity_tolerance: 0.002
initpose: [-0.145, 0.00, 0.50, 90, 90, 0]
keyposes:
  - [-0.295, -0.02, 0.40,  90,  60,   0]
  - [-0.195, -0.02, 0.40,  90,  75,   0]
  - [-0.145, -0.02, 0.40,  90,  90,   0]
  - [-0.095, -0.02, 0.40,  90, 105,   0]
  - [ 0.005, -0.02, 0.40,  90, 120,   0]
  - [-0.145,  0.13, 0.40,   0,  50, -90]
  - [-0.145,  0.08, 0.40,   0,  65, -90]
  - [-0.145, -0.04, 0.40,   0,  95, -90]
  - [-0.145, -0.08, 0.40,   0, 110, -90]
