mesh_generator:
  ros__parameters:
    screen_frame:      virtual_screen
    refenrece_frame:   world
    nsteps_u:          10
    nsteps_v:          10

robot_description_provider:
  ros__parameters:
    root_frame: base_link

nep_bridge:
  ros__parameters:
#    nep_ip:      10.66.171.39
    nep_ip:      192.168.1.11
    period:      0.1    # polling period of incoming NEP messages in seconds
    config_file: package://nep_bridge/config/sample_config.yaml
