arms:
  a_bot:
    type:               URe
    robot_ip:           "10.66.171.40"
    default_gripper:    a_bot_gripper
    initial_controller: scaled_joint_trajectory_controller
    consistent_controllers:
      - joint_state_broadcaster
      - motion_control_handle
    extra_consistent_controllers:
      # - force_torque_sensor_broadcaster
      - io_and_status_controller
      - speed_scaling_state_broadcaster
      - tcp_pose_broadcaster
      - ur_configuration_controller
    inactive_controllers:
      - joint_trajectory_controller
      - forward_velocity_controller
      - forward_position_controller
      - cartesian_compliance_controller
      - cartesian_force_controller
      - cartesian_motion_controller
    extra_inactive_controllers:
      - force_mode_controller
      - passthrough_trajectory_controller
      - freedrive_mode_controller
      - tool_contact_controller

grippers:
  a_bot_gripper:
    type:                  RobotiqGripper
    device:                robotiq_140
    driver:                urcap
    ip_or_dev:             "10.66.171.40"
    slave_id:              "9"
    max_effort:            5.0
    velocity:              0.1
  precision_tools:
    type:                  DynamixelDevices
    usb_port:              "/dev/ttyUSB1"
    baud_rate:             "57600"
    tools:
      precision_tool:
        type:              PrecisionTool
        motor_id:          "1"
        base_link:         precision_tool/base_link
        tip_link:          precision_tool/tip_link

cameras:
  # a_motioncam:
  #   type: PhoXiCamera
  a_bot_camera:
    type: CodedLightRealsenseCamera

moveit_eef_step: 0.002
