arms:
  a_bot:
    type:               URe
    robot_ip:           "10.66.171.40"
    default_gripper:    a_bot_gripper
    initial_controller: a_bot_scaled_joint_trajectory_controller
    consistent_controllers:
      - a_bot_motion_control_handle
    extra_consistent_controllers:
      - a_bot_force_torque_sensor_broadcaster
      - a_bot_io_and_status_controller
      - a_bot_speed_scaling_state_broadcaster
      - a_bot_tcp_pose_broadcaster
      - a_bot_ur_configuration_controller
    inactive_controllers:
      - a_bot_joint_trajectory_controller
      - a_bot_forward_velocity_controller
      - a_bot_forward_position_controller
      - a_bot_cartesian_compliance_controller
      - a_bot_cartesian_force_controller
      - a_bot_cartesian_motion_controller
    extra_inactive_controllers:
      - a_bot_force_mode_controller
      - a_bot_passthrough_trajectory_controller
      - a_bot_freedrive_mode_controller
      - a_bot_tool_contact_controller

grippers:
  a_bot_gripper:
    type:            RobotiqGripper
    device:          robotiq_140
    driver:          urcap
    ip_or_dev:       "10.66.171.40"
    slave_id:        9
    client_args:
      max_effort:    5.0
      velocity:      0.1
  precision_tools:
    type:            DynamixelDevices
    param_file:      package://aist_fastening_tools/config/default.yaml
    grippers:
      precision_tool:
        type:        PrecisionTool
        client_args:
          base_link: precision_tool/base_link
          tip_link:  precision_tool/tip_link

cameras:
  # a_motioncam:
  #   type: PhoXiCamera
  a_bot_camera:
    type: CodedLightRealsenseCamera

moveit_eef_step: 0.002
