arms:
  a_bot:
    type:               URe
    robot_ip:           "10.66.171.40"
    default_gripper:    a_bot_gripper
    initial_controller: scaled_joint_trajectory_controller
    consistent_controllers:
      - joint_state_broadcaster
      - motion_control_handle
    # extra_consistent_controllers:
    #   - force_torque_sensor_broadcaster
    #   - io_and_status_controller
    #   - speed_scaling_state_broadcaster
    #   - tcp_pose_broadcaster
    #   - ur_configuration_controller
    # inactive_controllers:
    #   - joint_trajectory_controller
    #   - forward_velocity_controller
    #   - forward_position_controller
    #   - cartesian_compliance_controller
    #   - cartesian_force_controller
    #   - cartesian_motion_controller
    extra_inactive_controllers:
      - force_mode_controller
      - passthrough_trajectory_controller
      - freedrive_mode_controller
      - tool_contact_controller
  b_bot:
    type:               URe
    robot_ip:           "10.66.171.41"
    default_gripper:    b_bot_gripper
    initial_controller: scaled_joint_trajectory_controller
    consistent_controllers:
      - joint_state_broadcaster
      - motion_control_handle
    # extra_consistent_controllers:
    #   - force_torque_sensor_broadcaster
    #   - io_and_status_controller
    #   - speed_scaling_state_broadcaster
    #   - tcp_pose_broadcaster
    #   - ur_configuration_controller
    # inactive_controllers:
    #   - joint_trajectory_controller
    #   - forward_velocity_controller
    #   - forward_position_controller
    #   - cartesian_compliance_controller
    #   - cartesian_force_controller
    #   - cartesian_motion_controller
    extra_inactive_controllers:
      - force_mode_controller
      - passthrough_trajectory_controller
      - freedrive_mode_controller
      - tool_contact_controller

grippers:
  a_bot_gripper:
    type:                      RobotiqGripper
    device:                    robotiq_140
    driver:                    urcap
    ip_or_dev:                 "10.66.171.40"
    slave_id:                  9
    max_effort:                5.0
    velocity:                  0.1
  b_bot_gripper:
    type:                      RobotiqGripper
    device:                    robotiq_85
    driver:                    urcap
    ip_or_dev:                 "10.66.171.41"
    slave_id:                  9
    max_effort:                5.0
    velocity:                  0.1
  precision_tools:
    type:                      DynamixelDevices
    usb_port:                  "/dev/ttyUSB1"
    baud_rate:                 57600
    tools:
      precision_tool:
        type:                  PrecisionTool
        motor_id:              1
        base_link:             precision_tool/base_link
        tip_link:              precision_tool/tip_link
  screw_tools:
    type:                      DynamixelDevices
    usb_port:                  "/dev/ttyUSB0"
    baud_rate:                 1000000
    tools:
      screw_tool_m3_fastening:
        type:                  ScrewTool
        motor_id:              2
      screw_tool_m4_fastening:
        type:                  ScrewTool
        motor_id:              3
  suction_tools:
    type:                      URioDevices
    driver_ns:                 b_bot_io_and_status_controller
    tools:
      screw_tool_m3:
        type:                  SuctionGripper
        digital_in_port:       0
        digital_out_port_suck: 0
        digital_out_port_blow: 1
        base_link:             screw_tool_m3/base_link
        tip_link:              screw_tool_m3/tip_link
      screw_tool_m4:
        type:                  SuctionGripper
        digital_in_port:       1
        digital_out_port_suck: 2
        digital_out_port_blow: 3
        base_link:             screw_tool_m4/base_link
        tip_link:              screw_tool_m4/tip_link
      suction_tool:
        type:                  SuctionGripper
        digital_in_port:       2
        digital_out_port_suck: 4
        digital_out_port_blow: 5
        base_link:             suction_tool/base_link
        tip_link:              suction_tool/tip_link
      base_fixture:
        type:                  SuctionGripper
        digital_out_port_suck: 6
        joint_name:            base_fixture_piston_joint
        base_link:             base_fixture_base_link
        tip_link:              workbench_holder_link

cameras:
  a_motioncam:
    type: PhoXiCamera
  a_bot_camera:
    type: CodedLightRealsenseCamera
  b_bot_camera:
    type: CodedLightRealsenseCamera
  live_camera:
    type: USBCamera

moveit_eef_step: 0.002
