robots:
  a_bot:
    type:               UniversalRobot
    default_gripper:    a_bot_gripper
    initial_controller: scaled_joint_trajectory_controller
    consistent_controllers:
      - joint_state_broadcaster
      - io_and_status_controller
      - speed_scaling_state_broadcaster
      - force_torque_sensor_broadcaster
      - tcp_pose_broadcaster
      - ur_configuration_controller
    inactive_controllers:
      - joint_trajectory_controller
      - forward_velocity_controller
      - forward_position_controller
      - force_mode_controller
      - passthrough_trajectory_controller
      - freedrive_mode_controller
      - tool_contact_controller
  b_bot:
    type:            UniversalRobot
    default_gripper: b_bot_gripper
    initial_controller: scaled_joint_trajectory_controller
    consistent_controllers:
      - joint_state_broadcaster
      - io_and_status_controller
      - speed_scaling_state_broadcaster
      - force_torque_sensor_broadcaster
      - tcp_pose_broadcaster
      - ur_configuration_controller
    inactive_controllers:
      - joint_trajectory_controller
      - forward_velocity_controller
      - forward_position_controller
      - force_mode_controller
      - passthrough_trajectory_controller
      - freedrive_mode_controller
      - tool_contact_controller

grippers:
  a_bot_gripper:
    type:                    RobotiqGripper
    controller_ns:           a_bot_gripper_controller
    max_effort:              5.0
    velocity:                0.1
  b_bot_gripper:
    type:                    RobotiqGripper
    controller_ns:           b_bot_gripper_controller
    max_effort:              5.0
    velocity:                0.1
  precision_tool:
    type:                    PrecisionGripper
    controller_ns:           precision_tool_controller
    base_link:               precision_tool/base_link
    tip_link:                precision_tool/tip_link
  screw_tool_m3:
    type:                    ScrewTool
    controller_ns:           screw_tool_m3_controller
    fastening_controller_ns: screw_tool_m3_fastening_controller
    base_link:               screw_tool_m3/base_link
    tip_link:                screw_tool_m3/tip_link
  screw_tool_m4:
    type:                    ScrewTool
    controller_ns:           screw_tool_m4_controller
    fastening_controller_ns: screw_tool_m4_fastening_controller
    base_link:               screw_tool_m4/base_link
    tip_link:                screw_tool_m4/tip_link
  suction_tool:
    type:                    SuctionGripper
    controller_ns:           suction_tool_controller
    base_link:               suction_tool/base_link
    tip_link:                suction_tool/tip_link
  base_fixture:
    type:                    SuctionGripper
    controller_ns:           base_fixture_controller
    base_link:               base_fixture_base_link
    tip_link:                workbench_holder_link

cameras:
  a_motioncam:
    type: PhoXiCamera
  a_bot_camera:
    type: CodedLightRealSenseCamera
  b_bot_camera:
    type: CodedLightRealSenseCamera
#  a_bot_zivid:
#    type: ZividCamera

moveit_eef_step: 0.002
