arms:
  b_bot:
    type:               URe
    robot_ip:           "10.66.171.41"
    default_gripper:    b_bot_gripper
    initial_controller: b_bot_scaled_joint_trajectory_controller
    extra_consistent_controllers:
      - b_bot_force_torque_sensor_broadcaster
      - b_bot_io_and_status_controller
      - b_bot_speed_scaling_state_broadcaster
      - b_bot_tcp_pose_broadcaster
      - b_bot_ur_configuration_controller
    inactive_controllers:
      - b_bot_joint_trajectory_controller
      - b_bot_forward_velocity_controller
      - b_bot_forward_position_controller
    extra_inactive_controllers:
      - b_bot_force_mode_controller
      - b_bot_passthrough_trajectory_controller
      - b_bot_freedrive_mode_controller
      - b_bot_tool_contact_controller

grippers:
  b_bot_gripper:
    type:                    RobotiqGripper
    device:                  robotiq_85
    driver:                  urcap
    ip_or_dev:               "10.66.171.41"
    slave_id:                "9"
    controller_ns:           b_bot_gripper_controller
    max_effort:              5.0
    velocity:                0.1
  precision_tool:
    type:                    PrecisionGripper
    usb_port:                "/dev/ttyUSB1"
    motor_id:                "1"
    controller_ns:           precision_tool_controller
    base_link:               precision_tool/base_link
    tip_link:                precision_tool/tip_link
  screw_tool_m3:
    type:                    ScrewTool
    controller_ns:           screw_tool_m3_controller
    fastening_controller_ns: screw_tool_m3_fastening_controller
    base_link:               screw_tool_m3/base_link
    tip_link:                screw_tool_m3/tip_link
  screw_tool_m4:
    type:                    ScrewTool
    controller_ns:           screw_tool_m4_controller
    fastening_controller_ns: screw_tool_m4_fastening_controller
    base_link:               screw_tool_m4/base_link
    tip_link:                screw_tool_m4/tip_link
  suction_tool:
    type:                    SuctionGripper
    controller_ns:           suction_tool_controller
    base_link:               suction_tool/base_link
    tip_link:                suction_tool/tip_link
  base_fixture:
    type:                    SuctionGripper
    controller_ns:           base_fixture_controller
    base_link:               base_fixture_base_link
    tip_link:                workbench_holder_link

cameras:
  a_motioncam:
    type: PhoXiCamera
  b_bot_camera:
    type: CodedLightRealsenseCamera

moveit_eef_step: 0.002
