arms:
  b_bot:
    type:               URe
    robot_ip:           "10.66.171.41"
    default_gripper:    b_bot_gripper
    active_controller:  scaled_joint_trajectory_controller
    consistent_controllers:
      - joint_state_broadcaster
      - motion_control_handle
    extra_consistent_controllers:
      - force_torque_sensor_broadcaster
      - io_and_status_controller
      - speed_scaling_state_broadcaster
      - tcp_pose_broadcaster
      - ur_configuration_controller
    inactive_controllers:
      - forward_velocity_controller
      - forward_position_controller
      - cartesian_compliance_controller
      - cartesian_force_controller
      - cartesian_motion_controller
    extra_inactive_controllers:
      - joint_trajectory_controller
      - force_mode_controller
      - passthrough_trajectory_controller
      - freedrive_mode_controller
      - tool_contact_controller

grippers:
  b_bot_gripper:
    type:            RobotiqGripper
    device:          robotiq_85
    driver:          urcap
    ip_or_dev:       "10.66.171.41"
    slave_id:        9
    client_args:
      max_effort:    5.0
      velocity:      0.1
  screw_tools:
    type:            DynamixelDevices
    param_file:      package://aist_fastening_tools/config/default.yaml
    grippers:
      screw_tool_m3_fastening:
        type:        ScrewTool
        motor_id:    2
      screw_tool_m4_fastening:
        type:        ScrewTool
        motor_id:    3
  suction_tools:
    type:            URioDevices
    driver_ns:       b_bot_io_and_status_controller
    param_file:      package://aist_fastening_tools/config/default.yaml
    grippers:
      screw_tool_m3:
        type:        SuctionTool
        client_args:
          base_link: screw_tool_m3/base_link
          tip_link:  screw_tool_m3/tip_link
      screw_tool_m4:
        type:        SuctionTool
        client_args:
          base_link: screw_tool_m4/base_link
          tip_link:  screw_tool_m4/tip_link
      suction_tool:
        type:        SuctionTool
        client_args:
          base_link: suction_tool/base_link
          tip_link:  suction_tool/tip_link
      base_fixture:
        type:        SuctionTool
        client_args:
          base_link: base_fixture_base_link
          tip_link:  workbench_holder_link

cameras:
  a_motioncam:
    type: PhoXiCamera
  b_bot_camera:
    type: CodedLightRealsenseCamera
  live_camera:
    type: USBCamera

moveit_eef_step: 0.002
