controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm/joint_1
      - left_arm/joint_2
      - left_arm/joint_3
      - left_arm/joint_4
      - left_arm/joint_5
      - left_arm/joint_6
      - left_arm/joint_7
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_arm/joint_1
      - right_arm/joint_2
      - right_arm/joint_3
      - right_arm/joint_4
      - right_arm/joint_5
      - right_arm/joint_6
      - right_arm/joint_7
  - name: fake_torso_controller
    type: $(arg fake_execution_type)
    joints:
      - torso/joint_1
      - torso/joint_2
      - torso/joint_3
  - name: fake_head_controller
    type: $(arg fake_execution_type)
    joints:
      - head/joint_1
      - head/joint_2
      - head/joint_3
  - name: fake_torso_head_controller
    type: $(arg fake_execution_type)
    joints:
      - torso/joint_1
      - torso/joint_2
      - torso/joint_3
      - head/joint_1
      - head/joint_2
      - head/joint_3
  - name: fake_torso_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - torso/joint_1
      - torso/joint_2
      - torso/joint_3
      - left_arm/joint_1
      - left_arm/joint_2
      - left_arm/joint_3
      - left_arm/joint_4
      - left_arm/joint_5
      - left_arm/joint_6
      - left_arm/joint_7
  - name: fake_torso_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - torso/joint_1
      - torso/joint_2
      - torso/joint_3
      - right_arm/joint_1
      - right_arm/joint_2
      - right_arm/joint_3
      - right_arm/joint_4
      - right_arm/joint_5
      - right_arm/joint_6
      - right_arm/joint_7
  - name: fake_both_arms_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm/joint_1
      - left_arm/joint_2
      - left_arm/joint_3
      - left_arm/joint_4
      - left_arm/joint_5
      - left_arm/joint_6
      - left_arm/joint_7
      - right_arm/joint_1
      - right_arm/joint_2
      - right_arm/joint_3
      - right_arm/joint_4
      - right_arm/joint_5
      - right_arm/joint_6
      - right_arm/joint_7
  - name: fake_whole_body_controller
    type: $(arg fake_execution_type)
    joints:
      - torso/joint_1
      - torso/joint_2
      - torso/joint_3
      - head/joint_1
      - head/joint_2
      - head/joint_3
      - left_arm/joint_1
      - left_arm/joint_2
      - left_arm/joint_3
      - left_arm/joint_4
      - left_arm/joint_5
      - left_arm/joint_6
      - left_arm/joint_7
      - right_arm/joint_1
      - right_arm/joint_2
      - right_arm/joint_3
      - right_arm/joint_4
      - right_arm/joint_5
      - right_arm/joint_6
      - right_arm/joint_7
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: home_position
  - group: right_arm
    pose: home_position
  - group: torso
    pose: home_position
  - group: head
    pose: home_position
  - group: torso_head
    pose: home_position
  - group: torso_left_arm
    pose: home_position
  - group: torso_right_arm
    pose: home_position
  - group: both_arms
    pose: home_position
  - group: whole_body
    pose: home_position