<?xml version="1.0"?>
<package format="3">
  <name>aist_collision_object_manager</name>
  <version>1.0.0</version>
  <description>The aist_collision_object_manager package</description>

  <maintainer email="t.ueshiba@aist.go.jp">Toshio Ueshiba</maintainer>
  <license>BSD</license>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>shape_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>aist_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
