a_bot_camera:
  ros__parameters:
    serial_no:       "636203005853"
    camera_name:     a_bot_camera       # required for prefix of frame IDs
    usb_port_id:     ""
    device_type:     ""
    json_file_path:  ""
    rosbag_filename: ""

    enable_color:  true
    enable_depth:  true
    enable_sync:   true
    enable_infra1: false
    enable_gyro:   false
    enable_accel:  false

    align_depth:
      enable: true

    rgb_camera:
      color_profile: "640x480x30"
    depth_module:
      depth_profile: "640x480x30"  # D405, D435
      infra_profile: "848x480x60"  # D405, D435
    coded_light_depth_sensor:
      depth_profile: "640x480x30"  # SR305
      infra_profile: "640x480x30"  # SR305

    pointcloud:
      enable:                  false
      stream_filter:           RS2_STREAM_COLOR  # RS2_STREAM_ANY
      stream_index_filter:     0
      allow_no_texture_points: false
      ordered_pc:              false

    publish_tf:              true
    tf_publish_rate:         0.0  # 0 - static transform

    clip_distance:           -2.0
    linear_accel_cov:        0.01
    initial_reset:           false
    reconnect_timeout:       6.0
    wait_for_device_timeout: -1.0
    unite_imu_method:        0  # [0:none, 1:copy, 2:linear_interpolation]
    topic_odom_in:           odom_in
    calib_odom_file:         ""
    publish_odom_tf:         true
    depth_multiplier:        1.0
    depth_offset:            0.0

b_bot_camera:
  ros__parameters:
    serial_no:       "636203005303"
    camera_name:     b_bot_camera       # required for prefix of frame IDs
    usb_port_id:     ""
    device_type:     ""
    json_file_path:  ""
    rosbag_filename: ""

    enable_color:  true
    enable_depth:  true
    enable_sync:   true
    enable_infra1: false
    enable_gyro:   false
    enable_accel:  false

    align_depth:
      enable: true

    rgb_camera:
      color_profile: "640x480x30"
    depth_module:
      depth_profile: "640x480x30"  # D405, D435
      infra_profile: "848x480x60"  # D405, D435
    coded_light_depth_sensor:
      depth_profile: "640x480x30"  # SR305
      infra_profile: "640x480x30"  # SR305

    pointcloud:
      enable:                  false
      stream_filter:           RS2_STREAM_COLOR  # RS2_STREAM_ANY
      stream_index_filter:     0
      allow_no_texture_points: false
      ordered_pc:              false

    publish_tf:              true
    tf_publish_rate:         0.0  # 0 - static transform

    clip_distance:           -2.0
    linear_accel_cov:        0.01
    initial_reset:           false
    reconnect_timeout:       6.0
    wait_for_device_timeout: -1.0
    unite_imu_method:        0  # [0:none, 1:copy, 2:linear_interpolation]
    topic_odom_in:           odom_in
    calib_odom_file:         ""
    publish_odom_tf:         true
    depth_multiplier:        1.0
    depth_offset:            0.0

a_motioncam:
  ros__parameters:
    id:                          LTR-066
    trigger_mode:                1  # 0: Freerun, 1: Software, 2: Hardware
    intensity_scale:             0.5
    rate:                        20.0
    processing_settings:
      normals_estimation_radius: 2
    output_settings:
      send_point_cloud:          true
      send_normal_map:           true
      send_depth_map:            true
      send_confidence_map:       false
      send_texture:              true
      send_color_camera_image:   true

/live_camera/usb_cam:
  ros__parameters:
    video_device:       /dev/video-livecam
    framerate:          5.0
    io_method:          mmap
    frame_id:           live_camera_optical_frame
    pixel_format:       mjpeg2rgb  # see usb_cam/supported_formats for list of supported formats
    av_device_format:   YUV422P
    image_width:        1920
    image_height:       1080
    camera_name:        usb_cam
    camera_info_url:    package://aist_description/scenes/calib/live_camera-camera_info.yaml
    brightness:         -1
    contrast:           -1
    saturation:         -1
    sharpness:          -1
    gain: -1
    auto_white_balance: true
    white_balance:      4000
    autoexposure:       true
    exposure:           100
    autofocus:          false
    focus:              -1