a_bot_gripper:
  device:       robotiq_140
  driver:       urcap
  ip_or_dev:    "10.66.171.40"
  slave_id:     9

b_bot_gripper:
  device:       robotiq_85
  driver:       urcap
  ip_or_dev:    "10.66.171.41"
  slave_id:     9
