# Goal
string                    robot_name
string                    subframe_link
geometry_msgs/PoseStamped pose
bool                      pick
float64[]                 offset
float64[]                 approach_offset
float64[]                 departure_offset
float64                   speed_fast
float64                   speed_slow
---
# Result
string stage  # 'move', 'approach', 'grasp/release', 'depart', 'verify'
---
# Feedback
string stage  # 'move', 'approach', 'grasp/release', 'depart', 'verify'
