# Goal
string   robot_name
string   eef_link
float32  angle_increment   # number of waypoints per revolution
float32  radius_increment  # increment of radius per revolution
float32  radius_max        # maximum radius
float32  speed
float32  accel
duration timeout
---
# Result
---
# Feedback
