ur_type:             ur5e
robot_ip:            "10.66.171.41"
safety_limits:       true
safety_pos_margin:   0.15
reverse_port:        50005
script_sender_port:  50006
reverse_ip:          "0.0.0.0"
script_command_port: 50008
trajectory_port:     50007
initial_positions:   [1.5708, -2.1, 1.4, -0.85, -1.5708, 0.0]
