<?xml version="1.0"?>
<package format="3">

  <name>aist_visualization</name>
  <version>0.1.0</version>
  <description>The aist_visualization package</description>

  <maintainer email="t.ueshiba@aist.go.hp">Toshio Ueshiba</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rclcpp_components</build_depend>
  <exec_depend>rclcpp_components</exec_depend>

  <depend>pluginlib</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>shape_msgs</depend>
  <depend>aist_msgs</depend>
  <depend>libqt5-widgets</depend>
  <depend>rviz_common</depend>
  <depend>rviz_default_plugins</depend>
  <depend>rviz_rendering</depend>
  <depend>rviz_ogre_vendor</depend>
  <depend>cv_bridge</depend>
  <depend>ddynamic_reconfigure2</depend>
  <depend>urdf</depend>
  <depend>aist_utility</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
